# Generated by Django 5.0.6 on 2024-12-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('C', 'Complete'), ('P', 'Pending'), ('R', 'Received')], default='R', max_length=1),
        ),
    ]
